import cv2
from PIL import Image
import numpy as np
frame = cv2.imread("combined.png")
cv2.imshow("try",cv2.resize(frame,(1020,1620)))
cv2.waitKey(0)
exit()
frame = cv2.imread("cooler.jpg")
# frame = cv2.imread("cooler.jpg")
cv2.imshow("that",frame)
# print(frame.getpixel(50,50,50))
print(frame.shape)
cv2.waitKey(0)
ret, frame = cv2.threshold(frame,127,255,cv2.THRESH_BINARY)
cv2.imshow("that",cv2.resize(frame,(860,540)))
cv2.waitKey(0)
# print(frame.getpixel(50,50,50))
print(frame.shape)

kernel = np.ones((25,25),np.uint8)
frame = cv2.morphologyEx(frame, cv2.MORPH_OPEN, kernel)
cv2.imshow("that",cv2.resize(frame,(860,540)))
cv2.waitKey(0)
img = cv2.imread("websitetree.png")
print(img.shape,";")
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
new = cv2.inRange(hsv, (18,100,0), (100,255,255))
output = cv2.bitwise_and(img, img, mask=new)

# frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
cv2.imwrite("websitecolored.png",output)
cv2.imshow("ds",cv2.resize(output,(860,540)))
cv2.waitKey(0)
kernel = np.ones((8,8),np.uint8)
# output = cv2.morphologyEx(output, cv2.MORPH_OPEN, kernel)
# output = cv2.morphologyEx(output, cv2.MORPH_CLOSE, kernel)
# output = cv2.morphologyEx(output, cv2.MORPH_CLOSE, kernel)
# output = cv2.morphologyEx(output, cv2.MORPH_CLOSE, kernel)
# output = cv2.morphologyEx(output, cv2.MORPH_CLOSE, kernel)
# output = cv2.morphologyEx(output, cv2.MORPH_CLOSE, kernel)
# output = cv2.morphologyEx(output, cv2.MORPH_CLOSE, kernel)
cv2.imshow("ds",cv2.resize(output,(860,540)))
cv2.waitKey(0)
kernel = np.ones((5,5),np.uint8)
output = cv2.bitwise_and(frame,output)
output = cv2.dilate(output,kernel,iterations = 1)
cv2.imshow("ds",cv2.resize(output,(860,540)))
cv2.waitKey(0)
exit()
frame = cv2.adaptiveThreshold(frame, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                                          cv2.THRESH_BINARY,5,2)
cv2.imshow("ds",cv2.resize(frame,(500,500)))

# imshow("C:\Users\Aryan Joshi\Downloads\TreeDrone-master\TreeDrone-master\RealCVImages\Undistorted\Frame142.png","trial")
